### ISSUE TITLE
fix vulnerability

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/xxxid#3]
- Delete package-lock.json
- Run `npm install`
- Commit the updated package-lock.json
- Create pull request

**Comment by rewa15** [comment]
We should not delete package-lock.json. Instead,
revert your changes in package-lock.json
stash your changes
pull most recent code version
run npm install for all the dependencies 
unstash your changes.

**Comment by arshadkazmi42** [comment]
thank you for the detailed response information. it will help people understand more

i have written steps in most simple way possible so it will be easy for new contributors to make their first PR

Feel free to send a PR for this if you want.

**Comment by mittulmandhan** [comment]
@arshadkazmi42 Can I work on it?

**Comment by arshadkazmi42** [comment]
i think @rewa15 has already started working on it

**Comment by arshadkazmi42** [comment]
@rewa15 any updates on this? If you are not working on it. May be @mittulmandhan can take it over?

**Comment by arshadkazmi42** [comment]
Fixed. Released v1.0.1
